// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function accumulate(f, elements) {
  if (elements) {
    return /* :: */[
            Curry._1(f, elements[0]),
            accumulate(f, elements[1])
          ];
  } else {
    return /* [] */0;
  }
}

exports.accumulate = accumulate;
/* No side effect */
